name: copyable
description: A Flutter package for giving and standardizing copy functionality to Dart classes.
version: 0.0.2
author: Juan Diego Fajardo <jfajardo@mit.edu>
homepage: https://github.com/kuanfajardo/copier.git

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.8
  # Generator
  analyzer: ^0.39.0
  build: ^1.3.0
  source_gen: ^0.9.5
  code_builder: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

